[package]
name = "aoc-2024-03"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
regex= "1.11.1"


[lints]
workspace = true